const SET_TOP_FREE_APP = 'SET_TOP_FREE_APP';
const SET_RECOMMAND_APP = 'SET_RECOMMAND_APP';
const SET_LOADED = 'SET_LOADED';
const LOAD_MORE = 'LOAD_MORE';

export { SET_TOP_FREE_APP, SET_RECOMMAND_APP, SET_LOADED, LOAD_MORE };
