const SET_TOP_FREE_APP = 'SET_TOP_FREE_APP';
const SET_RECOMMAND_APP = 'SET_RECOMMAND_APP';
const SET_LOADED = 'SET_LOADED';
const LOAD_MORE = 'LOAD_MORE';
const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

export {
  SET_TOP_FREE_APP,
  SET_RECOMMAND_APP,
  SET_LOADED,
  LOAD_MORE,
  SET_SEARCH_TERM,
};
